name: Setup Node.js
description: Setup Node.js with cache and pnpm

runs:
  using: composite
  steps:
    - name: Setup Node.js LTS
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
      with:
        node-version: lts/*
    - name: Setup pnpm
      uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
      id: pnpm-install
      with:
        version: 8
        run_install: false
    - name: Restore dependences cache
      uses: actions/cache/restore@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
      id: restore-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-dependences-${{ hashFiles('pnpm-lock.yaml') }}
    - name: Install dependencies
      if: steps.restore-dependences-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Save dependences cache
      if: steps.restore-dependences-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
      id: save-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-dependences-${{ hashFiles('pnpm-lock.yaml') }}
