name: Setup Node.js
description: Setup Node.js with cache and pnpm

inputs:
  node-version:
    description: Used Node.js version
    required: true
    default: lts/*

runs:
  using: composite
  steps:
    - name: Enable corepack
      run: corepack enable
      shell: bash
    - name: Setup Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version: ${{ inputs.node-version }}
    - name: Restore dependences cache
      uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      id: restore-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-dependences-${{ hashFiles('pnpm-lock.yaml') }}
    - name: Install dependencies
      if: steps.restore-dependences-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Save dependences cache
      # Execute cache by default branch only.
      if: ${{ github.ref_name == github.event.repository.default_branch && steps.restore-dependences-cache.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      id: save-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-dependences-${{ hashFiles('pnpm-lock.yaml') }}
