name: Setup Node.js
description: Setup Node.js with cache and pnpm

inputs:
  node-version:
    description: Used Node.js version
    required: true
    default: lts/*

runs:
  using: composite
  steps:
    - name: Enable corepack
      run: corepack enable
      shell: bash
    - name: Setup Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: ${{ inputs.node-version }}
    - name: Restore dependences cache
      uses: actions/cache/restore@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      id: restore-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-dependences-${{ hashFiles('pnpm-lock.yaml') }}
    - name: Install dependencies
      if: steps.restore-dependences-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Save dependences cache
      if: steps.restore-dependences-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      id: save-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-dependences-${{ hashFiles('pnpm-lock.yaml') }}
