x-USERNAME: &USERNAME node

services:
  workspace:
    init: true
    user: *USERNAME
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 16-bullseye
        USERNAME: *USERNAME
        WORKING_DIR: /workspace
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker-host.sock
      - type: bind
        source: ..
        target: /workspace
      - type: volume
        source: node_modules
        target: /workspace/node_modules
      - type: volume
        source: vscode_extensions
        target: /home/node/.vscode-server/extensions
      - type: volume
        source: zsh_history
        target: /home/node/commandhistory
    entrypoint: /bin/sh -c
    command: >
      "sleep infinity"

volumes:
  node_modules:
  vscode_extensions:
  zsh_history:
