name: Setup Bun
description: Setup Bun

runs:
  using: composite
  steps:
    - name: Setup Node.js LTS
      uses: oven-sh/setup-bun@d3603274aca5625baad52ec06108517a089cdd00 # v1
    - name: Restore dependences cache
      uses: actions/cache/restore@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
      id: restore-bun-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-bun-dependences-${{ hashFiles('pnpm-lock.yaml') }}
    - name: Install dependencies
      if: steps.restore-bun-dependences-cache.outputs.cache-hit != 'true'
      run: bun install
      shell: bash
    - name: Save dependences cache
      if: steps.restore-bun-dependences-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
      id: save-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-bun-dependences-${{ hashFiles('pnpm-lock.yaml') }}
