name: Setup Bun
description: Setup Bun

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
    - name: Restore dependences cache
      uses: actions/cache/restore@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
      id: restore-bun-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-bun-dependences-${{ hashFiles('**/bun.lock') }}
    - name: Install dependencies
      # bun.lock is not included in this repository.
      if: ${{ !contains(steps.restore-bun-dependences-cache.outputs.cache-matched-key, steps.restore-bun-dependences-cache.outputs.cache-primary-key) }}
      run: bun install
      shell: bash
    - name: Save dependences cache
      # Execute cache by default branch only.
      if: ${{ github.ref_name == github.event.repository.default_branch && !contains(steps.restore-bun-dependences-cache.outputs.cache-matched-key, steps.restore-bun-dependences-cache.outputs.cache-primary-key) }}
      uses: actions/cache/save@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
      id: save-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-bun-dependences-${{ hashFiles('**/bun.lock') }}
