name: Setup Bun
description: Setup Bun

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
    - name: Restore dependences cache
      uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      id: restore-bun-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-bun-dependences-${{ hashFiles('pnpm-lock.yaml') }}
    - name: Install dependencies
      if: steps.restore-bun-dependences-cache.outputs.cache-hit != 'true'
      run: bun install
      shell: bash
    - name: Save dependences cache
      if: steps.restore-bun-dependences-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      id: save-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-bun-dependences-${{ hashFiles('pnpm-lock.yaml') }}
