name: Setup Bun
description: Setup Bun

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
    - name: Restore dependences cache
      uses: actions/cache/restore@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      id: restore-bun-dependences-cache
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-dependences-${{ hashFiles('**/bun.lockb') }}
    - name: Install dependencies
      if: steps.restore-bun-dependences-cache.outputs.cache-hit != 'true'
      run: bun install
      shell: bash
    - name: Save dependences cache
      if: steps.restore-bun-dependences-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      id: save-dependences-cache
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-dependences-${{ hashFiles('**/bun.lockb') }}
