runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # tag=v2.2.4
      with:
        version: 7
    - name: Setup Node.js LTS
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
      with:
        node-version: lts/*
        cache: pnpm
    - name: Dependency install
      run: pnpm install --frozen-lockfile
      shell: bash
