runs:
  using: 'composite'
  steps:
    - name: Setup Node.js LTS
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        node-version: lts/*
    - name: Setup pnpm
      uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
      id: pnpm-install
      with:
        version: 8
        run_install: false
    - name: Restore dependences cache
      uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      id: restore-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-dependences-${{ hashFiles('pnpm-lock.yaml') }}
    - name: Dependency install
      if: steps.restore-dependences-cache.outputs.cache-hit != 'true'
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Save dependences cache
      if: steps.restore-dependences-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      id: save-dependences-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-dependences-${{ hashFiles('pnpm-lock.yaml') }}
