runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@537643d491d20c2712d11533497cb47b2d0eb9d5 # tag=v2.2.3
      with:
        version: 7
    - name: Setup Node.js LTS
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
      with:
        node-version: lts/*
        cache: pnpm
    - name: Dependency install
      run: pnpm install --frozen-lockfile
      shell: bash
