name: 'Auto Assign'
run-name: '${{ github.workflow }} (${{ github.ref_name }}): ${{ github.event.pull_request.title }}'
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: kentaro-m/auto-assign-action@f4648c0a9fdb753479e9e75fc251f507ce17bb7e # v2.0.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
