name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - .husky/**
      - public/**
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - .husky/**
      - public/**

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Setup Node.js LTS
        uses: actions/setup-node@b287e177c940f854dde9dcea09c4428a6d5edcf0 # v3.3.0
        with:
          node-version: lts/*
          cache: yarn
      - name: Dependency install
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
