name: CI
run-name: '${{ github.workflow }} (${{ github.ref_name }}): ${{ github.event.pull_request.title }}'
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

env:
  NODE_VERSION: '20'

# Declare default permissions as read only.
permissions: read-all

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: read
    outputs:
      typescript: ${{ steps.filter.outputs.typescript }}
      renovate-config: ${{ steps.filter.outputs.renovate-config }}
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Initialize
        uses: ./.github/actions/setup-bun
      - name: Check diff targets by path filters
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            typescript:
              - 'pnpm-lock.yaml'
              - '**/tsconfig*.json'
              - '**/*.ts'
              - '**/*.tsx'
            renovate-config:
              - '.github/renovate.json'

  renovate-config-lint:
    name: Renovate config lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [setup]
    if: ${{ needs.setup.outputs.renovate-config == 'true' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            .github/actions/setup-node-and-pnpm/action.yml
            .github/renovate.json
            package.json
            pnpm-lock.yaml
            prettier.config.mjs
          sparse-checkout-cone-mode: false
      - name: Initialize
        uses: ./.github/actions/setup-node-and-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Check format by Prettier
        run: pnpm exec prettier --check .github/renovate.json
      - name: Validate Renovate config
        run: pnpm --package renovate dlx renovate-config-validator --strict

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: [setup]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Initialize
        uses: ./.github/actions/setup-bun
      - name: Run format check
        run: bun run lint:prettier
      - name: Run lint
        run: bun run lint:eslint

  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: [setup]
    if: ${{ needs.setup.outputs.typescript == 'true' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Initialize
        uses: ./.github/actions/setup-bun
      - name: Run type check
        run: bun run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [lint, typecheck]
    if: ${{ !(failure() || contains(needs.*.result, 'cancelled')) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Initialize
        uses: ./.github/actions/setup-bun
      - name: Run test
        run: bun run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@d168679d447a7d9f9917d4b26caf2cfbf080cfb4 # v5.0.6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
