name: Snyk
run-name: ${{ github.workflow }} (${{ github.ref_name }})
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

# Declare default permissions as read only.
permissions: read-all

jobs:
  snyk:
    name: Check for vulnerabilities with Snyk
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    permissions:
      # * Needed to upload the results to code-scanning dashboard.
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Initialize
        uses: ./.github/actions/init
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@7fad562681122205233d1242c3bb39598c5393da # tag=0.3.0
        # * To make sure that SARIF upload gets called.
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@d186a2a36cc67bfa1b860e6170d37fb9634742c7 # v2.2.11
        with:
          sarif_file: snyk.sarif
