name: Snyk
run-name: ${{ github.workflow }} (${{ github.ref_name }})
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

# Declare default permissions as read only.
permissions: read-all

jobs:
  snyk:
    name: Check for vulnerabilities with Snyk
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ !github.event.pull_request.draft }}
    permissions:
      # * Needed to upload the results to code-scanning dashboard.
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Initialize
        uses: ./.github/actions/setup-node-and-pnpm
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@8349f9043a8b7f0f3ee8885bf28f0b388d2446e8 # V0.4.0
        # * To make sure that SARIF upload gets called.
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@df5a14dc28094dc936e103b37d749c6628682b60 # v3.25.0
        with:
          sarif_file: snyk.sarif
