name: Snyk
run-name: ${{ github.workflow }} (${{ github.ref_name }})
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

env:
  NODE_VERSION: '20'

# Declare default permissions as read only.
permissions: read-all

jobs:
  snyk:
    name: Check for vulnerabilities with Snyk
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ !github.event.pull_request.draft }}
    permissions:
      # * Needed to upload the results to code-scanning dashboard.
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Initialize
        uses: ./.github/actions/setup-node-and-pnpm
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@cdb760004ba9ea4d525f2e043745dfe85bb9077e # V0.4.0
        # * To make sure that SARIF upload gets called.
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@f779452ac5af1c261dce0346a8f964149f49322b # v3.26.13
        with:
          sarif_file: snyk.sarif
